### ISSUE TITLE
[Bug] Im playing SP and when i leave and join Chunk loader wouldnt load

### ISSUE THREAD

**Issue by lNoxyl** [SuperMartijn642/ChunkLoaders#31]
Hello im playing single player world and i use these chunk loaders to load my automatical farms. But when i leave and join chunk loaders  will disselect the chunks i want to be loaded and dont load any of them. Could someone help me what to do because i cant be in the nether, overworld or end an wait so much minutes to get like a stack of carrots golden nuggets or that saomething.
Please help.

**Comment by SuperMartijn642** [comment]
Please fill in the info in the template next time.
What version of Minecraft are you playing on?
What version of Chunk Loaders are you using?

**Comment by madjoe1976** [comment]
hi.. same here... java server 1.18.1 ,chunkloaders-1.1.7-mc1.18
after server restart chunks not loaded have to tick the map @chunkloader interface

**Comment by SuperMartijn642** [comment]
I fixed it now for Minecraft 1.18 in version 1.1.7a.

Thank you for reporting the issue and thanks you @madjoe1976 for more details!

**Comment by madjoe1976** [comment]
sorry.. its not fixed... now you cant enable it anymore @chunkloader mapinterface or. do we have to craft new one?

**Comment by SuperMartijn642** [comment]
Whoops 🤦‍♂️
It should work now in 1.1.7b for Minecraft 1.18.

**Comment by madjoe1976** [comment]
confirm.. its fixed now.. thx for your fast reaction... great work
